-- Drop and recreate the database
IF EXISTS (SELECT name FROM sys.databases WHERE name = 'airline_nds')
BEGIN
    ALTER DATABASE airline_nds SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE airline_nds;
END
GO

CREATE DATABASE airline_nds;
GO

USE airline_nds;
GO

-- Create NDS_Airlines table
CREATE TABLE NDS_Airlines (
    IATA_CODE_SK INT IDENTITY(1,1) PRIMARY KEY,
    IATA_CODE VARCHAR(10) NOT NULL,
    AIRLINE VARCHAR(100),
    SOURCE_ID VARCHAR(50),
    STATUS INT DEFAULT 1,
    CREATED DATETIME2 DEFAULT GETDATE(),
    MODIFIED DATETIME2 DEFAULT GETDATE(),
    CONSTRAINT UQ_NDS_Airlines_IATA_CODE UNIQUE (IATA_CODE)
);
GO

-- Create NDS_Airports table
CREATE TABLE NDS_Airports (
    IATA_CODE_SK INT IDENTITY(1,1) PRIMARY KEY,
    IATA_CODE VARCHAR(10) NOT NULL,
    AIRPORT VARCHAR(100),
    CITY VARCHAR(100),
    STATE CHAR(2),
    COUNTRY VARCHAR(50),
    LATITUDE DECIMAL(10,6),
    LONGITUDE DECIMAL(10,6),
    SOURCE_ID VARCHAR(50),
    STATUS INT DEFAULT 1,
    CREATED DATETIME2 DEFAULT GETDATE(),
    MODIFIED DATETIME2 DEFAULT GETDATE(),
    CONSTRAINT UQ_NDS_Airports_IATA_CODE UNIQUE (IATA_CODE)
);
GO

-- Create NDS_Flights table
CREATE TABLE NDS_Flights (
    FLIGHT_SK INT IDENTITY(1,1) PRIMARY KEY,
    DATE DATE,
    ORIGIN_AIRPORT INT NOT NULL,
    DESTINATION_AIRPORT INT NOT NULL,
    FLIGHT_NUMBER VARCHAR(10),
    TAIL_NUMBER VARCHAR(20),
    AIRLINE VARCHAR(10),
    SCHEDULED_DEPARTURE INT,
    DEPARTURE_TIME FLOAT,
    DEPARTURE_DELAY FLOAT,
    TAXI_OUT FLOAT,
    WHEELS_OFF FLOAT,
    SCHEDULED_TIME FLOAT,
    ELAPSED_TIME FLOAT,
    AIR_TIME FLOAT,
    DISTANCE FLOAT,
    WHEELS_ON FLOAT,
    TAXI_IN FLOAT,
    SCHEDULED_ARRIVAL INT,
    ARRIVAL_TIME FLOAT,
    ARRIVAL_DELAY FLOAT,
    DIVERTED INT,
    CANCELLED INT,
    CANCELLATION_REASON VARCHAR(1),
    AIR_SYSTEM_DELAY FLOAT,
    SECURITY_DELAY FLOAT,
    AIRLINE_DELAY FLOAT,
    LATE_AIRCRAFT_DELAY FLOAT,
    WEATHER_DELAY FLOAT,
    SOURCE_ID VARCHAR(50),
    STATUS INT DEFAULT 1,
    CREATED DATETIME2 DEFAULT GETDATE(),
    MODIFIED DATETIME2 DEFAULT GETDATE(),
    
    -- Foreign key constraints
    CONSTRAINT FK_NDS_Flights_OriginAirport 
        FOREIGN KEY (ORIGIN_AIRPORT) REFERENCES NDS_Airports(IATA_CODE_SK),
    CONSTRAINT FK_NDS_Flights_DestinationAirport 
        FOREIGN KEY (DESTINATION_AIRPORT) REFERENCES NDS_Airports(IATA_CODE_SK)
);
GO

PRINT 'Database airline_nds created successfully with all NDS tables!';
GO